#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width	0
bspc config window_gap		0
bspc config focused_border_color \#404040
bspc config normal_border_color  \#000000
#bspc config focus_follows_pointer false

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop=^6 follow=off focus=off state=floating
bspc rule -a discord desktop=^5 follow=off focus=off
bspc rule -a csgo desktop=^5 focus=on
bspc rule -a lutris follow=off focus=off state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a spotify desktop=^9 follow=off focus=off

feh --bg-fill ~/Wallpapers/osxlight.jpg &
wmname LG3D &
xsetroot -cursor_name left_ptr &
picom --no-fading-openclose &
nbfc start
#conky -c "/home/burak/.conky/NVIDIA BIOS/Arch Gotham" &
#eww daemon &
#eww open-many quit_main system player player_control profile date &
#dunst &
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
# tmux &
